#!/bin/bash

# Function to submit a job with optional dependency
submit_job() {
    local job_name="$1"
    local script="$2"
    local dependency="$3"

    mkdir -p logs

    if [ -z "$dependency" ]; then
        bsub -J "$job_name" \
             -o "logs/${job_name}_%J.out" \
             -e "logs/${job_name}_%J.err" \
             < "$script"
    else
        bsub -J "$job_name" \
             -w "done(${dependency})" \
             -o "logs/${job_name}_%J.out" \
             -e "logs/${job_name}_%J.err" \
             < "$script"
    fi
}

# Submit a single standalone job
submit_job run_liana lrp/routes/run-liana.sh ""
